dir=/home/axioncs/Downloads/aria2
continue=true
max-connection-per-server=16
split=16
min-split-size=5M
file-allocation=falloc
summary-interval=5
max-overall-download-limit=0
enable-rpc=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-allow-origin-all=true
rpc-secret=yuiopi
