vo=gpu-next
gpu-api=vulkan
hwdec=vaapi
gpu-context=waylandvk
tone-mapping=bt.2390
hdr-compute-peak=yes
target-colorspace-hint=no
video-sync=display-resample
interpolation=yes
tscale=oversample
sub-font="Netflix Sans"
sub-bold=yes
sub-font-size=35
sub-shadow-offset=1
sub-color="#FFFFFF"
