key=D
active=no

# Client ID for icons (playing, paused, etc).
# Visit https://discord.com/developers/applications to create your own.
# Default: 1328997690339758141
client_id=1328997690339758141

# Path to the mpv-discord binary.
binary_path=/home/pun_pun/.config/mpv/discord

# Path to the socket file used for communication with mpv-discord.
# Default: /tmp/mpvsocket
socket_path=/tmp/mpvsocket

# Use a static socket path instead of a dynamic per-pid one.
# Default: yes
use_static_socket_path=yes

# Time in seconds before hiding the presence when playback is paused.
# Set to 0 to disable.
# Default: 0
autohide_threshold=0
